export { Home } from './home/home.component'
export { Navigation } from './navigation/navigation.component'
export { Authentication } from './authentication/authentication.component'
export { Shop } from './shop/shop.component'
export { Checkout } from './checkout/checkout.component'
export { CategoriesPreview } from './categories-preview/categories-preview.component'
export { Category } from './category/category.component'
