export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'users/SET_CURRENT_USER',
  CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
  GOOGLE_SING_IN_START: 'user/GOOGLE_SING_IN_START',
  EMAIL_SING_IN_START: 'user/EMAIL_SING_IN_START',
  SING_IN_SUCCESS: 'user/SING_IN_SUCCESS',
  SING_IN_FAILED: 'user/SING_IN_FAILED'
}
