export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: 'caterogy/FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'caterogy/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'caterogy/FETCH_CATEGORIES_FAILED'
}
